ALTER TABLE EMPLOYEES
    ADD FOREIGN KEY (user_id)
    REFERENCES USERS(id)
        ON DELETE CASCADE;

ALTER TABLE EMPLOYEES
    ADD FOREIGN KEY (seller_id)
    REFERENCES SELLERS(id)
        ON DELETE CASCADE;

ALTER TABLE PRODUCT_CATEGORIES
    ADD FOREIGN KEY (product_id)
    REFERENCES PRODUCTS(id)
        ON DELETE CASCADE;

ALTER TABLE PRODUCT_CATEGORIES
    ADD FOREIGN KEY (category_id)
    REFERENCES CATEGORIES(id)
        ON DELETE CASCADE;

ALTER TABLE PRODUCT_INGREDIENTS
    ADD FOREIGN KEY (product_id)
    REFERENCES PRODUCTS(id)
        ON DELETE CASCADE;

ALTER TABLE PRODUCT_INGREDIENTS
    ADD FOREIGN KEY (ingredient_id)
    REFERENCES INGREDIENTS(id)
        ON DELETE CASCADE;

ALTER TABLE SELLER_PRODUCTS
    ADD FOREIGN KEY (seller_id)
    REFERENCES SELLERS(id)
        ON DELETE CASCADE;

ALTER TABLE SELLER_PRODUCTS
    ADD FOREIGN KEY (product_id)
    REFERENCES PRODUCTS(id)
        ON DELETE CASCADE;

ALTER TABLE ORDERS
    ADD FOREIGN KEY (seller_id)
    REFERENCES SELLERS(id)
        ON DELETE CASCADE;

ALTER TABLE ORDERS
    ADD FOREIGN KEY (user_id)
    REFERENCES USERS(id)
        ON DELETE CASCADE;

ALTER TABLE ORDERS
    ADD FOREIGN KEY (order_status_id)
    REFERENCES ORDER_STATUS(id)
        ON DELETE CASCADE;

ALTER TABLE ORDER_PRODUCTS
    ADD FOREIGN KEY (order_id)
    REFERENCES ORDERS(id)
        ON DELETE CASCADE;

ALTER TABLE ORDER_PRODUCTS
    ADD FOREIGN KEY (product_id)
    REFERENCES PRODUCTS(id)
        ON DELETE CASCADE;