CREATE TABLE IF NOT EXISTS USERS (
    id IDENTITY NOT NULL PRIMARY KEY,
    username VARCHAR2(100) NOT NULL,
    password VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    first_name VARCHAR2(100),
    last_name VARCHAR2(100),
    address VARCHAR2(100) NOT NULL,
    phone VARCHAR2(100) NOT NULL,
    birth_date DATE,
    is_user_seller BOOLEAN,
    is_user_admin BOOLEAN
);

CREATE TABLE IF NOT EXISTS EMPLOYEES (
    id IDENTITY NOT NULL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
    id IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR2(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCT_CATEGORIES (
    id IDENTITY NOT NULL PRIMARY KEY,
    product_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORIES (
    id IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR2(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCT_INGREDIENTS (
    id IDENTITY NOT NULL PRIMARY KEY,
    product_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS INGREDIENTS (
    id IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR2(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS SELLERS (
    id IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    address VARCHAR2(100) NOT NULL,
    phone VARCHAR2(100)
);

CREATE TABLE IF NOT EXISTS SELLER_PRODUCTS (
    id IDENTITY NOT NULL PRIMARY KEY,
    seller_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDERS (
    id IDENTITY NOT NULL PRIMARY KEY,
    seller_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    order_status_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDER_STATUS (
    id IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR2(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDER_PRODUCTS (
    id IDENTITY NOT NULL PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL
);

ALTER TABLE EMPLOYEES
    ADD FOREIGN KEY (user_id)
    REFERENCES USERS(id)
        ON DELETE CASCADE;

ALTER TABLE EMPLOYEES
    ADD FOREIGN KEY (seller_id)
    REFERENCES SELLERS(id)
        ON DELETE CASCADE;

ALTER TABLE PRODUCT_CATEGORIES
    ADD FOREIGN KEY (product_id)
    REFERENCES PRODUCTS(id)
        ON DELETE CASCADE;

ALTER TABLE PRODUCT_CATEGORIES
    ADD FOREIGN KEY (category_id)
    REFERENCES CATEGORIES(id)
        ON DELETE CASCADE;

ALTER TABLE PRODUCT_INGREDIENTS
    ADD FOREIGN KEY (product_id)
    REFERENCES PRODUCTS(id)
        ON DELETE CASCADE;

ALTER TABLE PRODUCT_INGREDIENTS
    ADD FOREIGN KEY (ingredient_id)
    REFERENCES INGREDIENTS(id)
        ON DELETE CASCADE;

ALTER TABLE SELLER_PRODUCTS
    ADD FOREIGN KEY (seller_id)
    REFERENCES SELLERS(id)
        ON DELETE CASCADE;

ALTER TABLE SELLER_PRODUCTS
    ADD FOREIGN KEY (product_id)
    REFERENCES PRODUCTS(id)
        ON DELETE CASCADE;

ALTER TABLE ORDERS
    ADD FOREIGN KEY (seller_id)
    REFERENCES SELLERS(id)
        ON DELETE CASCADE;

ALTER TABLE ORDERS
    ADD FOREIGN KEY (user_id)
    REFERENCES USERS(id)
        ON DELETE CASCADE;

ALTER TABLE ORDERS
    ADD FOREIGN KEY (order_status_id)
    REFERENCES ORDER_STATUS(id)
        ON DELETE CASCADE;

ALTER TABLE ORDER_PRODUCTS
    ADD FOREIGN KEY (order_id)
    REFERENCES ORDERS(id)
        ON DELETE CASCADE;

ALTER TABLE ORDER_PRODUCTS
    ADD FOREIGN KEY (product_id)
    REFERENCES PRODUCTS(id)
        ON DELETE CASCADE;